In [1]:
# MediFlow Cloud - Healthcare Data Analysis

# Import Libraries
import pandas as pd
import numpy as np

# Load Dataset
df = pd.read_csv("../data/raw/hospital_data.csv")

# Preview Data
print("Dataset Preview")
df.head()

Dataset Preview

,patient_id,age,gender,department,disease,length_of_stay,readmitted,hospital_city
0,1,69,Male,ICU,Fracture,11,1,Houston
1,2,32,Male,ICU,Diabetes,12,0,New York
2,3,89,Female,Emergency,Stroke,8,0,Los Angeles
3,4,78,Male,Emergency,Heart Disease,1,0,Dallas
4,5,38,Female,Neurology,Infection,1,0,Los Angeles

# Dataset Information

In [2]:
print("Dataset Info")
df.info()

Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      10000 non-null  int64
 1   age             10000 non-null  int64
 2   gender          10000 non-null  object
 3   department      10000 non-null  object
 4   disease         10000 non-null  object
 5   length_of_stay  10000 non-null  int64
 6   readmitted      10000 non-null  int64
 7   hospital_city   10000 non-null  object
dtypes: int64(4), object(4)
memory usage: 625.1+ KB

# Summary Statistics

In [3]:
print("Summary Statistics")
df.describe()

Summary Statistics

        patient_id           age  length_of_stay    readmitted
count  10000.00000  10000.000000    10000.000000  10000.000000
mean    5000.50000     53.539700        7.541200      0.203300
std     2886.89568     20.757324        3.999863      0.402474
min        1.00000     18.000000        1.000000      0.000000
25%     2500.75000     36.000000        4.000000      0.000000
50%     5000.50000     53.000000        8.000000      0.000000
75%     7500.25000     72.000000       11.000000      0.000000
max    10000.00000     89.000000       14.000000      1.000000

# Department Distribution

In [4]:
print("Department Distribution")
df['department'].value_counts()

Department Distribution

department
Orthopedics    2069
ICU            2031
Cardiology     1986
Emergency      1967
Neurology      1947
Name: count, dtype: int64

# Readmission Distribution

In [5]:
print("Readmission Distribution")
df['readmitted'].value_counts()

Readmission Distribution

readmitted
0    7967
1    2033
Name: count, dtype: int64